# Generated by Django 5.2.2 on 2025-06-11 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('working_hours', models.CharField(max_length=100, verbose_name='ساعات العمل')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='رابط الخريطة')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='رابط واتساب')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='رابط إنستغرام')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'بيانات التواصل',
                'verbose_name_plural': 'بيانات التواصل',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_logo', models.ImageField(upload_to='store_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_2', models.TextField(blank=True, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_3', models.TextField(blank=True, null=True)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_4', models.TextField(blank=True, null=True)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_5', models.TextField(blank=True, null=True)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_6', models.TextField(blank=True, null=True)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_7', models.TextField(blank=True, null=True)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_8', models.TextField(blank=True, null=True)),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_9', models.TextField(blank=True, null=True)),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description_10', models.TextField(blank=True, null=True)),
                ('video_1', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('description_11', models.TextField(blank=True, null=True)),
                ('video_2', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('description_12', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='api.color')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='api.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.size')),
            ],
        ),
    ]
