# Generated by Django 5.2.2 on 2025-06-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='admin_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
